#*******************************************************************************
#*  # Copyright (c) 2016 {UPRC}.
#*  # All rights reserved. This program and the accompanying materials
#*  # are made available under the terms of the The MIT License (MIT).
#*  # which accompanies this distribution, and is available at
#*  # http://opensource.org/licenses/MIT
#*
#*  # Contributors:
#*  #    {Constantinos Patsakis} {UPRC}
#*  #    {Stamatis Glykos} {UPRC}
#*  #    {Constantinos Alexandris} {UPRC}
#*  # Initially developed in the context of OPERANDO EU project www.operando.eu 
#*******************************************************************************/

#repositoryManagers:
#- { name: built-in, schema: https, host: snf-706921.vm.okeanos.grnet.gr, port: 8443, serviceRoot: /dan }
#- { name: AMI, schema: https, host: snf-706921.vm.okeanos.grnet.gr, port: 8443, serviceRoot: /dan }
repositoryManagers:
- name: built-in
  schema: https
  host: snf-706921.vm.okeanos.grnet.gr
  port: 8443
  serviceRoot: /op-pdr-rpm/
- name: AMI
  schema: https
  host: snf-706921.vm.okeanos.grnet.gr
  port: 8443
  serviceRoot: /op-pdr-rpm/